#!/usr/bin/env python3
"""Estimate LLM token usage and cost for the homework grading endpoint."""

import argparse
import os
from pathlib import Path
from statistics import mean
from autograder import build_grading_prompt, extract_notebook_content, load_rubric
from dotenv import load_dotenv


DEFAULT_INPUT_PRICE_PER_MILLION = 0.15
DEFAULT_OUTPUT_PRICE_PER_MILLION = 0.60
DEFAULT_OUTPUT_TOKENS = 600
WORKLOADS = (50, 100, 150)


def estimate_tokens(text: str, chars_per_token: float) -> int:
    return max(1, round(len(text) / chars_per_token))


def sample_submission_paths(root: Path) -> list[Path]:
    paths = sorted((root / "submission_tests").glob("*.ipynb"))
    if paths:
        return paths
    template = root / "GW08_table3_two_cols_student_template.ipynb"
    return [template] if template.exists() else []


def money(value: float) -> str:
    return f"${value:,.4f}"


def build_report(root: Path, chars_per_token: float, output_tokens: int,
                 input_price: float, output_price: float) -> str:
    load_dotenv(root / ".env")
    assignment = extract_notebook_content(str(root / "GW08_table3_two_cols.ipynb"))["prompt_text"]
    rubric = load_rubric(str(root / "rubric_gw.txt"))
    system_prompt = "You are a strict grading assistant. Return valid JSON only, no extra text."
    submission_paths = sample_submission_paths(root)
    if not submission_paths:
        raise FileNotFoundError("No submission notebook found for the input-token sample.")

    prompts = []
    submission_char_counts = []
    for path in submission_paths:
        submission = extract_notebook_content(str(path))["prompt_text"]
        submission_char_counts.append(len(submission))
        prompt = build_grading_prompt(assignment, submission, rubric)
        prompts.append(system_prompt + prompt)

    input_tokens = round(mean(estimate_tokens(prompt, chars_per_token) for prompt in prompts))
    input_cost = input_tokens * input_price / 1_000_000
    output_cost = output_tokens * output_price / 1_000_000
    cost_per_submission = input_cost + output_cost
    model = os.getenv("MODEL_NAME", "gpt-4o-mini")
    base_url = os.getenv("GROQ_BASE_URL") or os.getenv("OPENAI_BASE_URL")
    if not base_url and os.getenv("GROQ_API_KEY", "").strip():
        base_url = "https://api.groq.com/openai/v1"
    endpoint = (base_url or "https://api.openai.com/v1").rstrip("/") + "/chat/completions"

    lines = [
        "# Estimated API Token Cost Per Homework Submission",
        "",
        "Generated by `estimate_api_cost.py` from the live prompt builder.",
        "",
        "## Cost Breakdown",
        "",
        "| API endpoint | Target model | Input tokens/sub | Output tokens/sub | Cost/sub | Total 50 | Total 100 | Total 150 |",
        "|---|---|---:|---:|---:|---:|---:|---:|",
        f"| `{endpoint}` | `{model}` | {input_tokens:,} | {output_tokens:,} | {money(cost_per_submission)} | {money(cost_per_submission * 50)} | {money(cost_per_submission * 100)} | {money(cost_per_submission * 150)} |",
        "",
        "## Total Project Cost",
        "",
        "| Students/submissions | Estimated input tokens | Estimated output tokens | Total cost |",
        "|---:|---:|---:|---:|",
    ]
    for students in WORKLOADS:
        lines.append(f"| {students} | {input_tokens * students:,} | {output_tokens * students:,} | {money(cost_per_submission * students)} |")

    lines += [
        "",
        "## Assumptions and Edge Cases",
        "",
        f"- One successful `POST /grade` request makes one application-level call to `chat.completions.create`; there are no application retry loops or multi-turn calls.",
        f"- Input tokens are estimated as `round(characters / {chars_per_token:g})`, including the strict system prompt and the constructed user prompt. The estimate averages {len(prompts)} notebook sample(s): `submission_tests/*.ipynb` when present.",
        f"- The sampled student payload averages {mean(submission_char_counts):,.0f} characters; the prompt also includes the full assignment ({len(assignment):,} characters), rubric JSON, grading rules, and extracted cell outputs. Actual usage varies with code, markdown, and output length.",
        f"- Output is modeled at {output_tokens:,} tokens for JSON grading breakdown plus final feedback. The code does not set `max_tokens`; measure `usage.completion_tokens` in production for billing accuracy.",
        f"- Pricing defaults to OpenAI `gpt-4o-mini` standard rates of `${input_price:.2f}/1M` input and `${output_price:.2f}/1M` output tokens (see [OpenAI API pricing](https://openai.com/api/pricing/)). Override with `INPUT_PRICE_PER_MILLION`, `OUTPUT_PRICE_PER_MILLION`, and `OUTPUT_TOKENS` if using another provider/model.",
        "- The OpenAI SDK can retry some transient failures internally. This report excludes failed/retried requests; multiply by the observed request-attempt factor if provider logs show retries. A failed request may still be billable depending on provider behavior.",
        "- Cached-input discounts, batch pricing, taxes, credits, rate-limit fees, and provider-specific free tiers are excluded.",
        "",
        "## Reproduce",
        "",
        "```sh",
        "python estimate_api_cost.py",
        "python estimate_api_cost.py --chars-per-token 3.5 --output-tokens 800",
        "```",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parent)
    parser.add_argument("--chars-per-token", type=float, default=4.0)
    parser.add_argument("--output-tokens", type=int,
                        default=int(os.getenv("OUTPUT_TOKENS", DEFAULT_OUTPUT_TOKENS)))
    parser.add_argument("--input-price-per-million", type=float,
                        default=float(os.getenv("INPUT_PRICE_PER_MILLION", DEFAULT_INPUT_PRICE_PER_MILLION)))
    parser.add_argument("--output-price-per-million", type=float,
                        default=float(os.getenv("OUTPUT_PRICE_PER_MILLION", DEFAULT_OUTPUT_PRICE_PER_MILLION)))
    parser.add_argument("--output", type=Path, default=None,
                        help="Write Markdown to this path instead of stdout.")
    args = parser.parse_args()
    report = build_report(args.root, args.chars_per_token, args.output_tokens,
                          args.input_price_per_million, args.output_price_per_million)
    if args.output:
        args.output.write_text(report, encoding="utf-8")
    else:
        print(report, end="")


if __name__ == "__main__":
    main()